### PR TITLE
Created example.py

### PR DESCRIPTION
**Pull request by iamDyeus**
A Simple Python Script that generates Insults with the help of Evil Insult API

### CODE REVIEW

**Review by EvilInsultGenerator — APPROVED** [review]
Thank you so much for your input. It looks great! 😘

**Comment by EvilInsultGenerator** [comment]
Are you interested in adding language support into your script? 
May you do a GUI (e.g. with tkinter) too?

**Comment by iamDyeus** [comment]
I could but honestly speaking I am not good in tkinter at all.

**Comment by EvilInsultGenerator** [comment]
Don't worry, that is totally fine.
Do you prefer to desgin the UX yourself or should I ask someone to design it?
I heard of the project [Tkinter Designer](https://github.com/ParthJadhav/Tkinter-Designer) by @ParthJadhav. Maybe we could try that.

**Comment by ParthJadhav** [comment]
Haha, A insult generator. I am gonna try this.

**Comment by iamDyeus** [comment]
for the time being, I'll update the example.py script and **add Language Support** in it,  I also made a prototype thing for the GUI but I don't think I'll be the right guy for making It.

prototype

**Comment by EvilInsultGenerator** [comment]
> for the time being, I'll update the example.py script and **add Language Support** in it, I also made a prototype thing for the GUI but I don't think I'll be the right guy for making It.
> 
> prototype

That looks awesome! 👍

**Comment by iamDyeus** [comment]
hey dude,
i just made this GUI thing on figma, here : https://www.figma.com/file/uo781Lxy6Y6y2R6lED72ZQ/Evil-Insult-Generator?node-id=0%3A1

you can convert it using tkinter designer and use it, i would have done that... but the problem is that i am not very much familiar with tkinter library.

**Pull request merged**
